version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3000"
    environment:
      - JWT_SECRET=supersecret
  catalog-service:
    build: ./catalog-service
    ports:
      - "3002:3000"
  order-service:
    build: ./order-service
    ports:
      - "3003:3000"
    depends_on:
      - catalog-service
